### ISSUE TITLE
AJAX response from edd_ajax_recalculate_taxes tied to incorrect element 

### ISSUE THREAD

**Issue by dryan1144** [quaderno/quaderno-edd#11]
It appears that line 57 of edd-quardeno.js should reference `#edd_checkout_cart_form`, not `#edd_checkout_cart `. The response from`edd_checkout_cart()` (which is called via the AJAX function `edd_ajax_recalculate_taxes()`) includes the `#edd_checkout_cart_form` div in the HTML response itself, so you end up nesting the div over and over again unintentionally.

**Comment by polimorfico** [comment]
Hi there! Sorry for late reply. We just launched a [new version](https://wordpress.org/plugins/edd-quaderno/) (1.26.0) that implements that change. Thanks for your suggestion!
