### ISSUE TITLE
Tax ID field display overrides EDD Stripe's hide/show of address fields 

### ISSUE THREAD

**Issue by zak-wearecore** [quaderno/quaderno-edd#15]
This only happens if a user goes through EDD checkout with a saved address.  The EDD Stripe plugin hides all billing address fields, including edd_tax_id_wrap, on page load.  The EDD Quaderno JS interferes with this as it fires toggle_tax_id_fields() on the 'edd_gateway_loaded' JS event which causes the Tax ID field to be displayed when all other billing address fields are hidden

**Comment by polimorfico** [comment]
Hey! Thanks for letting us know. We just launched the [version 1.27.3](https://wordpress.org/plugins/edd-quaderno/) to fix this issue. 

Let us know if you need anything else. Happy to help.
