### ISSUE TITLE
EDD 3.0 compatibility

### ISSUE THREAD

**Issue by jakubmikita** [quaderno/quaderno-edd#16]
As a heads-up, the EDD team is working on plugin v3.0 and there's already [first beta published](https://easydigitaldownloads.com/development/2021/02/16/edd-3-0-beta1/).

I think this affects the Quaderno plugin as it stores custom meta within the Payment.

**Comment by polimorfico** [comment]
Hey Jakub!  We talked to the EDD team some weeks ago and we can confirm that our extension is already compatible with EDD 3.0. Please check it with their first beta and don't hesitate to contact us if you find any issue. Happy to help!

**Comment by jakubmikita** [comment]
Awesome, good to know!
