### ISSUE TITLE
Plugin installed admin notice: URL is not working

### ISSUE THREAD

**Issue by flowdee** [quaderno/quaderno-edd#18]
When you install your plugin, the URL in the admin notice isn't properly escaped.

<img width="1376" alt="Bildschirm­foto 2023-02-05 um 10 01 43" src="https://user-images.githubusercontent.com/2278756/216810385-631497e0-cd35-45dd-b7e5-148536e3052c.png">

**Comment by polimorfico** [comment]
Hey! Thanks for letting us know. We thought that message is no longer needed and we removed it in the last version.
