### ISSUE TITLE
Tax info is not saved in the payment details

### ISSUE THREAD

**Issue by jakubmikita** [quaderno/quaderno-edd#2]
The problem is that there's an inconsistency between the Quaderno invoice and EDD payment details.

Ie. someone purchases something, the Quaderno tax is set to 0 and invoice is generated without it while in payment details you can still see the tax, ie. 23%.

Maybe it's because I have the store set up in a way the total price is always the same (tax included).

To save the tax info I can get from Quaderno I created a simple snippet:

```
function edd_quaderno_tax_rewrite( $payment_id ) {

	$payment = new EDD_Payment( $payment_id );

	if ( $payment->total == 0 || ! function_exists( 'edd_quaderno_tax' ) ) {
		return;
	}

	$metadata   = $payment->get_meta();
	$vat_number = isset( $metadata['vat_number'] ) ? $metadata['vat_number'] : '';

	$tax = edd_quaderno_tax( $payment->address['country'], $payment->address['zip'], $vat_number );

	$tax_rate       = $tax->rate / 100;
	$total          = $payment->total;
	$net            = $total / ( 1 + $tax_rate );
	$tax            = $total - $net;

    // Update each product tax and total.
    foreach ( $payment->cart_details as $item_index => $item_details ) {

    	$item_total = $item_details['item_price'];
    	$item_net   = $item_total / ( 1 + $tax_rate );
    	$item_tax   = $item_total - $item_net;

    	$payment->modify_cart_item( $item_index, array(
    		'item_price' => $item_net,
    		'subtotal'   => $item_net * $item_details['quantity'],
    		'tax'        => $item_tax,
    	) );

    }

    // Update tax rate, tax total is calculated automatically when updating items.
    $payment->tax_rate = $tax_rate;
    $payment->subtotal = $net;
    $payment->total    = $total;

    $payment->save();

}
add_action( 'edd_complete_purchase', 'edd_quaderno_tax_rewrite', 100 );
add_action( 'edd_recurring_record_payment', 'edd_quaderno_tax_rewrite', 100 );
```

Note: this is untested and probably needs more logic like tax included/excluded and discounts handling.

**Comment by polimorfico** [comment]
We've made some test and taxes are calculated correctly even when they're included in the total price. Are you having this issue with new or old recurring payments?

**Comment by jakubmikita** [comment]
New payments, but the more I think about it the more I think it may be related more to EDD than to your plugin

**Comment by polimorfico** [comment]
I think so. Or maybe another plugin. Other users haven't reported anything related. 
I close this issue but let me know if you find anything new.

**Comment by jakubmikita** [comment]
@polimorfico I found a bug! To be clear: my business is in EU and I'm testing as a US customer using VPN.

EDD is set up with fallback rate 23% and tax included in price.

From Quaderno API we are getting:

```
stdClass Object
(
    [name] => 
    [rate] => 0
    [country] => US
    [region] => 
    [county] => 
    [transaction_type] => eservice
    [notes] => 
    [extra_name] => 
    [extra_rate] => 
)
```

While you are testing the tax name here: https://github.com/quaderno/quaderno-edd/blob/master/includes/taxes.php#L87

Because it's empty, the fallback rate is used while in Quaderno the invoice is created correctly.

**Comment by polimorfico** [comment]
@Kubitomakita This behavior is correct. If there isn't an explicit tax rate for a country, our plugin uses the EDD fallback rate. This allow users to apply a fallback rate to all their sales. If you don't want to charge US customers, you can set up a fallback rate of 0%. Does this make sense?

**Comment by jakubmikita** [comment]
Yep, this is how I do it now, thanks
