### ISSUE TITLE
Partial refunds: Credit Notes missing

### ISSUE THREAD

**Issue by flowdee** [quaderno/quaderno-edd#20]
![Bildschirm­foto 2023-03-26 um 11 17 01](https://user-images.githubusercontent.com/2278756/227770929-8b8b3f2d-61c3-459a-ac79-ce931a1938e1.png)

It looks like, when initiating a partial refund, no credit note is being created inside Quaderno

Using the latest versions.

**Comment by flowdee** [comment]
FYI @polimorfico

**Comment by polimorfico** [comment]
Thanks for letting us know. We'll take a look at this soon.

**Comment by polimorfico** [comment]
We updated our EDD extension to support partial refunds. It's already available in [version 1.33.0](https://wordpress.org/plugins/edd-quaderno/)
