### ISSUE TITLE
Fatal mistake when creating invoices

### ISSUE THREAD

**Issue by liquiem** [quaderno/quaderno-edd#23]
Hi @polimorfico , i am florian's colleague (@flowdee)

in some cases on our web sites (different server and different domain) the invoices are not generated. If you try to create them manually in EDD, the following critical error occurs:

`Fatal error: Uncaught Error: Too few arguments to function edd_quaderno_get_order_meta(), 1 passed in /sites/files/wp-content/plugins/edd-quaderno/includes/invoices.php on line 241 and exactly 2 expected
in /sites/files/wp-content/plugins/edd-quaderno/includes/order_details.php on line 54

Call stack:

edd_quaderno_get_order_meta()
wp-content/plugins/edd-quaderno/includes/invoices.php:241
edd_quaderno_process_recurring_payment()
wp-content/plugins/edd-quaderno/includes/invoices.php:264
edd_quaderno_resend_invoice()
wp-includes/class-wp-hook.php:308
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:332
WP_Hook::do_action()
wp-includes/plugin.php:517
do_action()
wp-content/plugins/easy-digital-downloads-pro/includes/admin/admin-actions.php:28
edd_process_actions()
wp-includes/class-wp-hook.php:308
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:332
WP_Hook::do_action()
wp-includes/plugin.php:517
do_action()
wp-admin/admin.php:175
require_once()
wp-admin/edit.php:10`

Do you have any idea?

Thanks, best,
Mirko

**Comment by polimorfico** [comment]
Hi, Mirko! Thanks for letting us know. We're already taking a look at this.

**Comment by liquiem** [comment]
@polimorfico Great! Thank you so much!

**Comment by polimorfico** [comment]
​We just deployed version 1.33.3 to fix this error. Sorry for all inconvenience 🙏

**Comment by liquiem** [comment]
Hey Carlos!

Great! You are insanely fast. Thank you for that! 

Works.
