### ISSUE TITLE
EDD Customer: Update VAT details

### ISSUE THREAD

**Issue by flowdee** [quaderno/quaderno-edd#26]
We regularly experience the issue that customers who got charged for renewal orders (subscriptions) automatically, receive invoices without VAT details.

The problem: When they purchased in the past, they forgot to add their details in the checkout. 

Even when we update the details directly via Quaderno (and create credit notes), next year, when subscription renewal hits, the invoices are created again without VAT details. I think it's because the data is missing in EDD?

It would be great if customers (and we EDD admins) could update VAT details (number and company name) via EDD.

### 1. Via the customer edit screen

![Bildschirmfoto 2023-11-02 um 09 25 18](https://github.com/quaderno/quaderno-edd/assets/2278756/eada1a2b-222e-45b3-824d-ea35f6c1eb93)

### 2. The customer themselves via profile edit screen

Shortcode: `[edd_profile_editor]`

![Bildschirmfoto 2023-11-02 um 09 24 22](https://github.com/quaderno/quaderno-edd/assets/2278756/072f3a7f-91b4-49a6-bd3f-b931c22363e3)

**Comment by flowdee** [comment]
Is there a little change to get this improvement? @polimorfico 

Would help a lot and save us a lot of weekly support tickets 🙏

**Comment by polimorfico** [comment]
Good news! We launched a new version (1.36.0) of the plugin to allow customers to edit their tax IDs and business names right from their "profile edit" screen. When a recurring order is renewed, we'll use the updated data to issue the final invoice.

Please check it out and let us know if you need anything else. Happy to help!

**Comment by flowdee** [comment]
@polimorfico thanks, looks fine!

But: Isn't it possible to give us admins the chance, to view + edit the company name + vat ID via the customer screen?

Customers often give us updated information, so our support team can double check + update from EDD as well. 

![279912920-eada1a2b-222e-45b3-824d-ea35f6c1eb93](https://github.com/quaderno/quaderno-edd/assets/2278756/5a26d3a1-0df2-4d10-ace1-1afc271326da)

**Comment by polimorfico** [comment]
@flowdee Unfortunately we haven't found a way to add custom fields to that form in the EDD dashboard. If you find out how to do it, please let us know, or feel free to send a PR and we'll be glad to evaluate it.
