### ISSUE TITLE
Warning: Undefined variable $tax in /includes/credits.php: edd_quaderno_create_credit

### ISSUE THREAD

**Issue by flowdee** [quaderno/quaderno-edd#28]
![Bildschirmfoto 2023-12-11 um 09 43 18](https://github.com/quaderno/quaderno-edd/assets/2278756/bd7ef1e0-3d9a-4e13-b9a4-a5a53b98c381)

action: `edd_process_refund_form`
data: `edd_process_refund=ff58f48ada&_wp_http_referer=%2Fwp-admin%2Fadmin-ajax.php&refund_order_item%5B%5D=46312&refund_order_item%5B46312%5D%5Bquantity%5D=1&refund_order_item%5B46312%5D%5Bsubtotal%5D=399.00&edd-paypal-refund=1&edd_recurring_cancel_subscription%5B10419%5D=10419`
order_id: `258516`

![Bildschirmfoto 2023-12-11 um 09 45 49](https://github.com/quaderno/quaderno-edd/assets/2278756/d6cb98aa-2f63-40f9-be67-978850bc7e01)

**Comment by flowdee** [comment]
@polimorfico looks like there occurs an error when creating credit notes with no tax orders.

**Comment by polimorfico** [comment]
@flowdee Thanks for letting me know! I'm checking this out and looking for a solution.

**Comment by polimorfico** [comment]
We just fixed this in version 1.36.0 🎉

Please check this out and let us know if you find any other issues.
