### ISSUE TITLE
Error: Call to a member function get_meta() on bool in edd_quaderno_process_recurring_payment at 235

### ISSUE THREAD

**Issue by flowdee** [quaderno/quaderno-edd#29]
![Bildschirmfoto 2024-07-02 um 10 31 20](https://github.com/quaderno/quaderno-edd/assets/2278756/10689327-4e5d-4f27-ba0f-f83ffd48ccbf)
![Bildschirmfoto 2024-07-02 um 10 32 23](https://github.com/quaderno/quaderno-edd/assets/2278756/990cd68e-e717-4575-bea1-bb1f730c8a63)

I checked the edd order and saw that for some reason, there was no customer assigned to. 

You may want to add a check to validate if `$customer = edd_get_customer( $order->customer_id )` returns proper results or break here.

**Comment by flowdee** [comment]
FYI @polimorfico

**Comment by polimorfico** [comment]
Thanks for letting us know. We fixed this issue in [version 1.37.3](https://wordpress.org/plugins/edd-quaderno/)
