### ISSUE TITLE
Billing State / Province is reset when EDD Quaderno is active

### ISSUE THREAD

**Issue by bporcelli** [quaderno/quaderno-edd#6]
If you checkout as a customer with a saved Billing State when EDD Quaderno is active, the saved state does not show up in the Billing State field. This happens because Quaderno triggers the change event on the #billing_country dropdown when the page loads, thus causing EDD to regenerate and replace the Billing State field.

**Comment by polimorfico** [comment]
Hey Brett! Thanks for letting us know. We're going to take a look to your PR as soon as possible.

**Comment by bporcelli** [comment]
No problem! Thanks for the quick response.
