### ISSUE TITLE
Update tax info for payment

### ISSUE THREAD

**Issue by jakubmikita** [quaderno/quaderno-edd#9]
Can Quaderno, while generating the invoice, update the subscription payment taxes (product tax and total tax)?

This would help to keep the data across the payments and invoices unified. Now ie. when tax ID is not valid the invoice can have different data than saved within the payment (VAT exempt).

**Comment by polimorfico** [comment]
What do you mean by subscription payment taxes? Can you please provide a use case?

**Comment by jakubmikita** [comment]
Sorry for the delayed response, I forgot to reply...

An example:

Before using Quaderno in my EDD store we billed basically everyone with VAT. We had a lot of transactions like PL company sells to USA individual. No VAT should be applied but in EDD, in old payment we have the VAT calculated. And this payment is a subscription payment.

Now, when we use Quaderno, and the subscription renews, the new transaction is created and new `Renewal` order placed in EDD which then triggers Quaderno to issue an invoice. The problem is that this renewed order will have VAT amount applied, while generated invoice in Quaderno will not.

The expected result is to update the payment meta back with details obtained from Quaderno. This means applying the correct VAT rate and amount.

I hope this makes sense now.

**Comment by polimorfico** [comment]
Sorry for the late reply. This issue should be fixed as Quaderno extension for EDD is calculating tax every time a new invoice is issued, no matter if it's one-off payment or a subscription.
